os: linux
dist: focal
language: node_js
node_js: node
script: yarn run compress
branches:
  only:
    - main
    - fix-travis
before_deploy:
  - git config --local user.name "UMass Transportation"
  - git config --local user.email "transportation-it@groups.umass.edu"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - gem update --system
  - gem install faraday-net_http
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: site.zip
  edge: true
  on:
    all_branches: true
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
